import type { Agent, AgentCategory, Review } from "./types";

export const CATEGORIES: {
  slug: AgentCategory;
  label: string;
  description: string;
}[] = [
  {
    slug: "coding",
    label: "Coding",
    description: "Agents that ship code, reviews, and migrations",
  },
  {
    slug: "research",
    label: "Research",
    description: "Deep briefings, citations, and synthesis",
  },
  {
    slug: "support",
    label: "Customer Support",
    description: "Ticket triage, replies, and escalation",
  },
  {
    slug: "marketing",
    label: "Marketing",
    description: "Campaigns, copy, and growth loops",
  },
  {
    slug: "trading",
    label: "Trading",
    description: "Market watchers and strategy assistants",
  },
  {
    slug: "design",
    label: "Design",
    description: "UI critique, assets, and brand systems",
  },
  {
    slug: "ops",
    label: "Operations",
    description: "Workflows, scheduling, and runbooks",
  },
  {
    slug: "education",
    label: "Education",
    description: "Tutors, coaches, and course builders",
  },
];

export const AGENTS: Agent[] = [
  {
    id: "forge-code",
    name: "Forge Code",
    tagline: "Senior engineer that lives in your PR queue",
    description:
      "Forge Code reviews pull requests, proposes patches, writes tests, and explains trade-offs in plain language. Tuned for TypeScript, Rust, and Python monorepos with CI-aware suggestions.",
    category: "coding",
    price: 49,
    pricingModel: "subscription",
    rating: 4.8,
    reviewCount: 2140,
    seller: "Lattice Labs",
    sellerVerified: true,
    capabilities: [
      "PR review",
      "Test generation",
      "Refactor plans",
      "CI failure triage",
    ],
    model: "Forge-Reasoning 4",
    tags: ["TypeScript", "Rust", "GitHub"],
    featured: true,
    bestseller: true,
    imageHue: 24,
    monthlyUsers: 128400,
  },
  {
    id: "atlas-brief",
    name: "Atlas Brief",
    tagline: "Research dossiers in under ten minutes",
    description:
      "Atlas Brief crawls trusted sources, ranks claims by confidence, and delivers board-ready memos with citations. Ideal for product, policy, and competitive intelligence teams.",
    category: "research",
    price: 79,
    pricingModel: "subscription",
    rating: 4.7,
    reviewCount: 986,
    seller: "Northwind Research",
    sellerVerified: true,
    capabilities: [
      "Source ranking",
      "Citation graphs",
      "Executive summaries",
      "Watchlists",
    ],
    model: "Atlas-R 2.1",
    tags: ["Reports", "Citations", "Watchlists"],
    featured: true,
    imageHue: 210,
    monthlyUsers: 64200,
  },
  {
    id: "hearth-desk",
    name: "Hearth Desk",
    tagline: "Support that sounds like your brand",
    description:
      "Hearth Desk drafts replies, tags urgency, and escalates edge cases with full conversation memory. Ships with tone profiles and knowledge-base sync for Zendesk and Intercom.",
    category: "support",
    price: 39,
    pricingModel: "subscription",
    rating: 4.6,
    reviewCount: 3122,
    seller: "Kindling Co.",
    sellerVerified: true,
    capabilities: [
      "Ticket triage",
      "Tone matching",
      "KB sync",
      "Escalation routing",
    ],
    model: "Hearth-Scribe 3",
    tags: ["Zendesk", "Intercom", "SLA"],
    bestseller: true,
    imageHue: 350,
    monthlyUsers: 210800,
  },
  {
    id: "pulse-campaign",
    name: "Pulse Campaign",
    tagline: "Launch-ready campaigns without the scramble",
    description:
      "Pulse Campaign builds briefs, channel calendars, ad variants, and landing copy from a single product brief. Includes A/B suggestion packs and performance hypotheses.",
    category: "marketing",
    price: 59,
    pricingModel: "subscription",
    rating: 4.5,
    reviewCount: 744,
    seller: "Beacon Studio",
    sellerVerified: true,
    capabilities: [
      "Campaign briefs",
      "Ad variants",
      "Calendar planning",
      "Hypothesis packs",
    ],
    model: "Pulse-M 1.8",
    tags: ["Ads", "Copy", "Growth"],
    featured: true,
    imageHue: 280,
    monthlyUsers: 48300,
  },
  {
    id: "ledger-scout",
    name: "Ledger Scout",
    tagline: "Market radar with risk notes attached",
    description:
      "Ledger Scout monitors instruments you choose, surfaces anomalies, and drafts risk notes with scenario tables. Built for discretionary traders who want signal—not autopilot trades.",
    category: "trading",
    price: 129,
    pricingModel: "subscription",
    rating: 4.4,
    reviewCount: 512,
    seller: "Meridian Quant",
    sellerVerified: true,
    capabilities: [
      "Anomaly alerts",
      "Scenario tables",
      "Risk notes",
      "Portfolio digests",
    ],
    model: "Ledger-Q 5",
    tags: ["Equities", "Crypto", "Alerts"],
    imageHue: 145,
    monthlyUsers: 22100,
  },
  {
    id: "canvas-critique",
    name: "Canvas Critique",
    tagline: "Design reviews with taste and specificity",
    description:
      "Canvas Critique evaluates layouts, hierarchy, accessibility, and brand fit. Returns annotated feedback and optional redesign prompts for Figma exports and screenshots.",
    category: "design",
    price: 45,
    pricingModel: "subscription",
    rating: 4.7,
    reviewCount: 891,
    seller: "Form & Field",
    sellerVerified: true,
    capabilities: [
      "UI critique",
      "A11y checks",
      "Brand fit",
      "Redesign prompts",
    ],
    model: "Canvas-Vision 2",
    tags: ["Figma", "A11y", "Brand"],
    newRelease: true,
    imageHue: 300,
    monthlyUsers: 31800,
  },
  {
    id: "runbook-pilot",
    name: "Runbook Pilot",
    tagline: "Ops playbooks that execute themselves",
    description:
      "Runbook Pilot turns messy wiki pages into executable checklists with ownership, SLAs, and postmortems. Integrates with Slack, PagerDuty, and your status page.",
    category: "ops",
    price: 69,
    pricingModel: "subscription",
    rating: 4.6,
    reviewCount: 603,
    seller: "Relay Systems",
    sellerVerified: true,
    capabilities: [
      "Playbook generation",
      "On-call assist",
      "Postmortems",
      "Status drafts",
    ],
    model: "Pilot-Ops 3.2",
    tags: ["Slack", "PagerDuty", "SRE"],
    featured: true,
    imageHue: 190,
    monthlyUsers: 27400,
  },
  {
    id: "mentor-loop",
    name: "Mentor Loop",
    tagline: "A patient tutor for any syllabus",
    description:
      "Mentor Loop adapts explanations to the learner, quizzes with spaced repetition, and tracks mastery. Great for onboarding engineers or shipping internal academies.",
    category: "education",
    price: 29,
    pricingModel: "subscription",
    rating: 4.8,
    reviewCount: 1540,
    seller: "Lumen Learning",
    sellerVerified: true,
    capabilities: [
      "Adaptive tutoring",
      "Quizzes",
      "Mastery tracking",
      "Syllabus import",
    ],
    model: "Mentor-E 4",
    tags: ["Onboarding", "LMS", "Quizzes"],
    bestseller: true,
    imageHue: 45,
    monthlyUsers: 156200,
  },
  {
    id: "diff-surgeon",
    name: "Diff Surgeon",
    tagline: "Surgical refactors for legacy codebases",
    description:
      "Diff Surgeon maps dependency risk, proposes incremental migration paths, and generates safe patch series you can land over weeks instead of weekends.",
    category: "coding",
    price: 99,
    pricingModel: "subscription",
    rating: 4.5,
    reviewCount: 421,
    seller: "Lattice Labs",
    sellerVerified: true,
    capabilities: [
      "Dependency maps",
      "Migration plans",
      "Patch series",
      "Risk scoring",
    ],
    model: "Forge-Reasoning 4",
    tags: ["Legacy", "Migrations", "Java"],
    imageHue: 12,
    monthlyUsers: 18900,
  },
  {
    id: "cite-weaver",
    name: "Cite Weaver",
    tagline: "Literature reviews with a paper trail",
    description:
      "Cite Weaver builds annotated bibliographies, contradiction maps, and claim matrices from PDFs and DOIs. Exports to Notion, Zotero, and Markdown.",
    category: "research",
    price: 12,
    pricingModel: "usage",
    rating: 4.6,
    reviewCount: 288,
    seller: "Northwind Research",
    sellerVerified: true,
    capabilities: [
      "PDF ingest",
      "Claim matrices",
      "Contradiction maps",
      "Zotero export",
    ],
    model: "Atlas-R 2.1",
    tags: ["Academic", "PDF", "Notion"],
    newRelease: true,
    imageHue: 200,
    monthlyUsers: 9400,
  },
  {
    id: "reply-craft",
    name: "Reply Craft",
    tagline: "Macro-quality replies without sounding canned",
    description:
      "Reply Craft drafts support macros that stay personal. Learns from your highest-rated agents and keeps compliance phrases locked.",
    category: "support",
    price: 24,
    pricingModel: "subscription",
    rating: 4.3,
    reviewCount: 1198,
    seller: "Kindling Co.",
    sellerVerified: false,
    capabilities: [
      "Macro drafting",
      "Compliance locks",
      "Tone learning",
      "QA scoring",
    ],
    model: "Hearth-Scribe 3",
    tags: ["Macros", "QA", "Compliance"],
    imageHue: 330,
    monthlyUsers: 87300,
  },
  {
    id: "hook-factory",
    name: "Hook Factory",
    tagline: "Scroll-stopping hooks tested before you ship",
    description:
      "Hook Factory generates short-form hooks, thumbnails concepts, and retention predictions for creators and growth teams.",
    category: "marketing",
    price: 19,
    pricingModel: "usage",
    rating: 4.4,
    reviewCount: 2066,
    seller: "Beacon Studio",
    sellerVerified: true,
    capabilities: [
      "Hook generation",
      "Thumbnail concepts",
      "Retention scores",
      "Platform packs",
    ],
    model: "Pulse-M 1.8",
    tags: ["Short-form", "Creators", "Hooks"],
    bestseller: true,
    imageHue: 265,
    monthlyUsers: 194500,
  },
  {
    id: "signal-desk",
    name: "Signal Desk",
    tagline: "Morning briefings for active desks",
    description:
      "Signal Desk delivers a curated open with movers, catalysts, and position-aware notes before the bell—or before Asia opens.",
    category: "trading",
    price: 89,
    pricingModel: "subscription",
    rating: 4.2,
    reviewCount: 334,
    seller: "Meridian Quant",
    sellerVerified: true,
    capabilities: [
      "Open briefings",
      "Catalyst calendar",
      "Position notes",
      "Desk chat",
    ],
    model: "Ledger-Q 5",
    tags: ["Futures", "FX", "Briefings"],
    imageHue: 160,
    monthlyUsers: 11200,
  },
  {
    id: "brand-compass",
    name: "Brand Compass",
    tagline: "Keep every asset on-brand",
    description:
      "Brand Compass scores copy and visuals against your brand kit, suggests safer alternatives, and flags off-voice language before launch.",
    category: "design",
    price: 55,
    pricingModel: "subscription",
    rating: 4.5,
    reviewCount: 467,
    seller: "Form & Field",
    sellerVerified: true,
    capabilities: [
      "Brand scoring",
      "Voice checks",
      "Asset review",
      "Guideline sync",
    ],
    model: "Canvas-Vision 2",
    tags: ["Brand kit", "Voice", "QA"],
    imageHue: 320,
    monthlyUsers: 24600,
  },
  {
    id: "queue-steward",
    name: "Queue Steward",
    tagline: "Intake that never drops the ball",
    description:
      "Queue Steward classifies requests, assigns owners, and nudges stalled work. Built for IT, facilities, and internal service desks.",
    category: "ops",
    price: 34,
    pricingModel: "subscription",
    rating: 4.4,
    reviewCount: 712,
    seller: "Relay Systems",
    sellerVerified: true,
    capabilities: [
      "Intake classification",
      "Owner assignment",
      "SLA nudges",
      "Weekly digests",
    ],
    model: "Pilot-Ops 3.2",
    tags: ["ITSM", "Intake", "SLA"],
    imageHue: 175,
    monthlyUsers: 39100,
  },
  {
    id: "fluency-coach",
    name: "Fluency Coach",
    tagline: "Conversation practice that corrects with care",
    description:
      "Fluency Coach runs spoken and written drills, scores clarity, and builds custom lesson plans for language learners and interview prep.",
    category: "education",
    price: 22,
    pricingModel: "subscription",
    rating: 4.7,
    reviewCount: 980,
    seller: "Lumen Learning",
    sellerVerified: true,
    capabilities: [
      "Speaking drills",
      "Clarity scoring",
      "Lesson plans",
      "Interview prep",
    ],
    model: "Mentor-E 4",
    tags: ["Languages", "Interview", "Speech"],
    newRelease: true,
    imageHue: 55,
    monthlyUsers: 72800,
  },
  {
    id: "schema-smith",
    name: "Schema Smith",
    tagline: "Database changes without the dread",
    description:
      "Schema Smith proposes migrations, rollback plans, and zero-downtime strategies with impact analysis across services.",
    category: "coding",
    price: 75,
    pricingModel: "subscription",
    rating: 4.6,
    reviewCount: 255,
    seller: "Lattice Labs",
    sellerVerified: true,
    capabilities: [
      "Migration drafts",
      "Rollback plans",
      "Impact analysis",
      "Zero-downtime paths",
    ],
    model: "Forge-Reasoning 4",
    tags: ["Postgres", "Prisma", "Migrations"],
    featured: true,
    imageHue: 200,
    monthlyUsers: 15300,
  },
  {
    id: "market-mapper",
    name: "Market Mapper",
    tagline: "Competitive landscapes that stay current",
    description:
      "Market Mapper builds living competitor maps from filings, product pages, hiring signals, and press—updated on a schedule you set.",
    category: "research",
    price: 149,
    pricingModel: "subscription",
    rating: 4.5,
    reviewCount: 190,
    seller: "Northwind Research",
    sellerVerified: true,
    capabilities: [
      "Competitor maps",
      "Hiring signals",
      "Press digests",
      "Scheduled refresh",
    ],
    model: "Atlas-R 2.1",
    tags: ["Competitive", "Strategy", "Maps"],
    imageHue: 220,
    monthlyUsers: 8700,
  },
  {
    id: "calm-queue",
    name: "Calm Queue",
    tagline: "De-escalate before tickets explode",
    description:
      "Calm Queue detects rising frustration, suggests softer phrasing, and routes to humans with a prepared context pack.",
    category: "support",
    price: 42,
    pricingModel: "subscription",
    rating: 4.5,
    reviewCount: 640,
    seller: "Kindling Co.",
    sellerVerified: true,
    capabilities: [
      "Sentiment detection",
      "De-escalation copy",
      "Human handoff",
      "Context packs",
    ],
    model: "Hearth-Scribe 3",
    tags: ["CX", "Sentiment", "Handoff"],
    imageHue: 340,
    monthlyUsers: 45600,
  },
  {
    id: "seo-orchard",
    name: "SEO Orchard",
    tagline: "Content clusters that actually rank",
    description:
      "SEO Orchard plans topic clusters, internal links, and briefs tuned to search intent—then grades drafts before publish.",
    category: "marketing",
    price: 64,
    pricingModel: "subscription",
    rating: 4.3,
    reviewCount: 833,
    seller: "Beacon Studio",
    sellerVerified: true,
    capabilities: [
      "Cluster planning",
      "Internal linking",
      "Draft grading",
      "Intent mapping",
    ],
    model: "Pulse-M 1.8",
    tags: ["SEO", "Content", "Clusters"],
    imageHue: 250,
    monthlyUsers: 51200,
  },
  {
    id: "risk-lantern",
    name: "Risk Lantern",
    tagline: "Portfolio stress tests in plain English",
    description:
      "Risk Lantern runs scenario shocks, explains drawdowns, and proposes hedges without executing trades on your behalf.",
    category: "trading",
    price: 199,
    pricingModel: "one-time",
    rating: 4.6,
    reviewCount: 142,
    seller: "Meridian Quant",
    sellerVerified: true,
    capabilities: [
      "Stress tests",
      "Drawdown explainers",
      "Hedge ideas",
      "Report export",
    ],
    model: "Ledger-Q 5",
    tags: ["Risk", "Hedges", "Reports"],
    featured: true,
    imageHue: 130,
    monthlyUsers: 6400,
  },
  {
    id: "layout-loom",
    name: "Layout Loom",
    tagline: "From wireframe notes to polished frames",
    description:
      "Layout Loom expands rough sketches into structured UI frames with spacing systems, component suggestions, and responsive notes.",
    category: "design",
    price: 9,
    pricingModel: "usage",
    rating: 4.4,
    reviewCount: 521,
    seller: "Form & Field",
    sellerVerified: false,
    capabilities: [
      "Wireframe expansion",
      "Spacing systems",
      "Component suggestions",
      "Responsive notes",
    ],
    model: "Canvas-Vision 2",
    tags: ["Wireframes", "UI", "Responsive"],
    imageHue: 290,
    monthlyUsers: 28700,
  },
  {
    id: "vendor-radar",
    name: "Vendor Radar",
    tagline: "Procurement diligence on autopilot",
    description:
      "Vendor Radar scores SaaS vendors on security, pricing drift, and renewal risk—then drafts negotiation briefs for finance and legal.",
    category: "ops",
    price: 119,
    pricingModel: "subscription",
    rating: 4.3,
    reviewCount: 176,
    seller: "Relay Systems",
    sellerVerified: true,
    capabilities: [
      "Vendor scoring",
      "Renewal alerts",
      "Negotiation briefs",
      "Security summaries",
    ],
    model: "Pilot-Ops 3.2",
    tags: ["Procurement", "SaaS", "Security"],
    newRelease: true,
    imageHue: 185,
    monthlyUsers: 9800,
  },
  {
    id: "skill-forge",
    name: "Skill Forge",
    tagline: "Internal academies that stay fresh",
    description:
      "Skill Forge turns SOPs into interactive courses with quizzes, certifications, and manager dashboards for skills coverage.",
    category: "education",
    price: 89,
    pricingModel: "subscription",
    rating: 4.6,
    reviewCount: 305,
    seller: "Lumen Learning",
    sellerVerified: true,
    capabilities: [
      "Course generation",
      "Certifications",
      "Manager dashboards",
      "SOP ingest",
    ],
    model: "Mentor-E 4",
    tags: ["L&D", "SOP", "Certs"],
    featured: true,
    imageHue: 40,
    monthlyUsers: 21400,
  },
];

export const REVIEWS: Review[] = [
  {
    id: "r1",
    agentId: "forge-code",
    author: "Maya Chen",
    rating: 5,
    title: "Cut our review latency in half",
    body: "Forge catches the subtle race conditions our juniors miss and writes clear review comments. Feels like a staff engineer on every PR.",
    date: "2026-06-12",
    verified: true,
  },
  {
    id: "r2",
    agentId: "forge-code",
    author: "Jonah Price",
    rating: 4,
    title: "Strong on TypeScript, improving on Rust",
    body: "Excellent for our Next.js services. Rust suggestions are good but occasionally conservative. Still worth every dollar.",
    date: "2026-05-28",
    verified: true,
  },
  {
    id: "r3",
    agentId: "atlas-brief",
    author: "Priya Nair",
    rating: 5,
    title: "Board memo quality",
    body: "We used Atlas for a competitive brief and the citation graph alone saved a week of analyst time.",
    date: "2026-07-02",
    verified: true,
  },
  {
    id: "r4",
    agentId: "hearth-desk",
    author: "Luis Ortega",
    rating: 5,
    title: "Sounds like us",
    body: "Tone profiles finally stick. Escalations arrive with context that our humans actually use.",
    date: "2026-06-19",
    verified: true,
  },
  {
    id: "r5",
    agentId: "mentor-loop",
    author: "Ava Brooks",
    rating: 5,
    title: "Best onboarding tutor we tried",
    body: "New hires reach productive week-two milestones faster. Quizzes adapt without feeling robotic.",
    date: "2026-07-14",
    verified: true,
  },
  {
    id: "r6",
    agentId: "pulse-campaign",
    author: "Noah Kim",
    rating: 4,
    title: "Great first drafts",
    body: "Campaign calendars are solid. We still rewrite ads, but the brief quality is consistently high.",
    date: "2026-04-30",
    verified: false,
  },
];

export function getAgentById(id: string): Agent | undefined {
  return AGENTS.find((agent) => agent.id === id);
}

export function getAgentsByCategory(category: AgentCategory): Agent[] {
  return AGENTS.filter((agent) => agent.category === category);
}

export function getFeaturedAgents(): Agent[] {
  return AGENTS.filter((agent) => agent.featured);
}

export function getBestsellers(): Agent[] {
  return AGENTS.filter((agent) => agent.bestseller);
}

export function getNewReleases(): Agent[] {
  return AGENTS.filter((agent) => agent.newRelease);
}

export function searchAgents(query: string): Agent[] {
  const q = query.trim().toLowerCase();
  if (!q) return AGENTS;
  return AGENTS.filter((agent) => {
    const haystack = [
      agent.name,
      agent.tagline,
      agent.description,
      agent.seller,
      agent.category,
      ...agent.tags,
      ...agent.capabilities,
    ]
      .join(" ")
      .toLowerCase();
    return haystack.includes(q);
  });
}

export function getReviewsForAgent(agentId: string): Review[] {
  return REVIEWS.filter((review) => review.agentId === agentId);
}
